name: Golang

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        env:
          dest: "root@103.74.5.27"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/deploy_key $dest "ls -la"

      - name: Git Pull
        env:
          dest: "root@103.74.5.27"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/deploy_key $dest "cd startup-be/ && eval \$(ssh-agent) && ssh-add ~/.ssh/vandyahmad24 && git pull origin master"

      - name: Docker Build
        env:
          dest: "root@103.74.5.27"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/deploy_key $dest "cd startup-be/ && docker build -t vandyahmad2404/startup-be:latest ."

      - name: Docker Run
        env:
          dest: "root@103.74.5.27"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/deploy_key $dest "cd startup-be/ && docker-compose up -d"
      
      
