name: SSH Command

on:
  push:
    branches:
      - master
jobs:
  ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "$DEPLOY_KEY" > ssh_key
        chmod 600 ssh_key
        eval $(ssh-agent -s)
        ssh-add ssh_key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    - name: SSH into the server
      run: ssh -o StrictHostKeyChecking=no root@${{secrets.HOST}} "ls -la"
